// GLOBAL GETTERS CONSTANTS
export const GET_STATE = 'GET_STATE';

// GLOBAL MUTATIONS CONSTANTS
export const SET_STATE = 'SET_STATE';

// GLOBAL ACTIONS CONSTANTS
export const SET_MODULE_STATE = 'SET_MODULE_STATE';
